publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/local/bin/ffmpeg
webServerPort: 8080

videoSettings:
  resolutionWidth: 900
  chunkLengthInSeconds: 4
  streamingKey: abc123

files:
  maxNumberInPlaylist: 30
  maxNumberOnDisk: 60

ipfs:
  enabled: false
  gateway: https://ipfs.io