publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/local/bin/ffmpeg
webServerPort: 8080

videoSettings:
  chunkLengthInSeconds: 4
  streamingKey: abc123
  encoderPreset: superfast # https://trac.ffmpeg.org/wiki/Encode/H.264
  passthrough: true # Enabling this will ignore the below stream qualities and pass through the same quality that you're sending it

  streamQualities:
    - bitrate: 6000k

files:
  maxNumberInPlaylist: 30

ipfs:
  enabled: false
  gateway: https://ipfs.io

s3:
  enabled: false
  endpoint: https://s3.us-west-2.amazonaws.com
  accessKey: ABC12342069
  secret: lolomgqwtf49583949
  region: us-west-2
  bucket: myvideo